### ISSUE TITLE
Bypass download from ftp://ftp.ensemblgenomes.org/

### ISSUE THREAD

**Issue by tvtv195** [DavidBSauer/OGT_prediction#10] opened 2023-09-19 22:33 UTC
Hi David,
We aim to install your tool on our servers and came across two main obstacles.  
1)The OGT_prediction tool is trying to download from ftp://ftp.ensemblgenomes.org/ which we can’t access from our servers through the firewall.
2) Our sysadmins are reluctant to install it at all, since they argue that any software which you have to run from the directory where the code resides is probably not going to be very robust.

Would be great if we could discuss these issues? 
Cheers Chris

**Comment by DavidBSauer** [comment] 2023-09-20 08:34
Hello Chris,
Happy to help here

1) There's no reason you can't manually download the genomes from ensembl, though it will be quite tedious to manually structure the genomes directory and build the genomes reference file for the script.
2) This is a philosophical difference between software versus scripts. 

For workaround, I would suggest running the prediction with a regression model that was pre-trained. If they really are obstinate about running on your system, happy to chat about further alternatives.

Best,
David

**Comment by tvtv195** [comment] 2023-09-21 05:17
Hi David,
Thanks for your quick reply and the explanation! 
What we have resolved 2) and have managed the following for 1):

script #1: we worked out from the code, that it was only downloading files ending .dna.toplevel.fa.gz, so we used BeautifulSoup to parse the html to locate that file for each sample. This only works if there is only 1 file with that ending in a folder, we don’t know enough about the structure of http://ftp.ensemblgenomes.org/pub/bacteria to know if that is a reasonable hypothesis?

script #2: We got the second script to work: it is using Entrez to get information from NCBI. However, the prediction_pipeline.py fails unless you comment out the step which tars up output directories and deletes the working data. We don’t know how important that is, but the output text file appears to be similar to the example output for the test data. It is unclear to us which model folder one should use and how the feature files are generated. The example model files don’t look the same as the feature files generated by feature_calculation_pipeline.py.

**Comment by tvtv195** [comment] 2023-09-21 23:04
To add to this, it seems that the problem is that it doesn't work consistently across ensemble genomes releases. Our dev said, "the example uses Release 40, which gives the expected results. Release 45 also works. Release 50 doesn’t work at all. Release 57 only matches 3 of the entries in the species.txt file."

**Comment by DavidBSauer** [comment] 2023-09-22 12:15
It looks like the Ensembl species list file is malformed for several releases. I have modified the genome retriever script to give an error message and quit when asked to use these releases.

Note, the number of genomes downloaded will vary with the Ensembl release. As I recall, they removed a number of genomes termed "redundant" a bit ago, which would have dramatically reduced the number of genomes available for some species.

**Comment by DavidBSauer** [comment] 2023-10-13 22:57
Closing as the above work-around appears to serve the purpose. But happy to reopen if necessary

**Closed as completed by DavidBSauer** 2023-10-13 22:57 UTC
